//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapUtilsFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapUtilsFluttifyPlugin (SubHandlerCustom)
- (NSDictionary<NSString*, Handler>*) getSubHandlerCustom;
@end

NS_ASSUME_NONNULL_END
