//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapUtilsFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapUtilsFluttifyPlugin (SubHandler0)
- (NSDictionary<NSString*, Handler>*) getSubHandler0;
@end

NS_ASSUME_NONNULL_END
