//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapUtilsFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapUtilsFluttifyPlugin (SubHandler2)
- (NSDictionary<NSString*, Handler>*) getSubHandler2;
@end

NS_ASSUME_NONNULL_END
