//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapUtilsFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapUtilsFluttifyPlugin (SubHandler1)
- (NSDictionary<NSString*, Handler>*) getSubHandler1;
@end

NS_ASSUME_NONNULL_END
