// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMK_NAVI_TYPE {
  BMK_NAVI_TYPE_NATIVE,
  BMK_NAVI_TYPE_WEB
}