// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKBuildInfo extends NSObject  {
  //region constants
  static const String name__ = 'BMKBuildInfo';

  @override
  final String tag__ = 'bmap_utils_fluttify';

  
  //endregion

  //region creators
  static Future<BMKBuildInfo?> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod(
      'ObjectFactory::createBMKBuildInfo',
      {'init': init}
    );
    return BmapUtilsFluttifyIOSAs<BMKBuildInfo?>(__result__);
  }
  
  static Future<List<BMKBuildInfo>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kBmapUtilsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchBMKBuildInfo',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => BmapUtilsFluttifyIOSAs<BMKBuildInfo>(it))
        .where((element) => element !=null)
        .cast<BMKBuildInfo>()
        .toList() ?? <BMKBuildInfo>[];
  }
  
  //endregion

  //region getters
  Future<double?> get_height() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_height", {'__this__': this});
    return __result__;
  }
  
  Future<int?> get_accuracy() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_accuracy", {'__this__': this});
    return __result__;
  }
  
  Future<String?> get_paths() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_paths", {'__this__': this});
    return __result__;
  }
  
  Future<String?> get_center() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_center", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'BMKBuildInfo{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension BMKBuildInfo_Batch on List<BMKBuildInfo> {
  String? get refId {
    if (isEmpty) return null;
    return first.refId;
  }

  //region getters
  Future<List<double?>> get_height_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_height_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<double?>().toList();
  }
  
  Future<List<int?>> get_accuracy_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_accuracy_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<int?>().toList();
  }
  
  Future<List<String?>> get_paths_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_paths_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<String?>> get_center_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKBuildInfo::get_center_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}