// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKFavPoiInfo extends NSObject  {
  //region constants
  static const String name__ = 'BMKFavPoiInfo';

  @override
  final String tag__ = 'bmap_utils_fluttify';

  
  //endregion

  //region creators
  static Future<BMKFavPoiInfo?> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod(
      'ObjectFactory::createBMKFavPoiInfo',
      {'init': init}
    );
    return BmapUtilsFluttifyIOSAs<BMKFavPoiInfo?>(__result__);
  }
  
  static Future<List<BMKFavPoiInfo>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kBmapUtilsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchBMKFavPoiInfo',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => BmapUtilsFluttifyIOSAs<BMKFavPoiInfo>(it))
        .where((element) => element !=null)
        .cast<BMKFavPoiInfo>()
        .toList() ?? <BMKFavPoiInfo>[];
  }
  
  //endregion

  //region getters
  Future<String?> get_favId() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_favId", {'__this__': this});
    return __result__;
  }
  
  Future<String?> get_poiName() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_poiName", {'__this__': this});
    return __result__;
  }
  
  Future<String?> get_poiUid() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_poiUid", {'__this__': this});
    return __result__;
  }
  
  Future<CLLocationCoordinate2D?> get_pt() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_pt", {'__this__': this});
    return BmapUtilsFluttifyIOSAs<CLLocationCoordinate2D>(__result__);
  }
  
  Future<String?> get_address() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_address", {'__this__': this});
    return __result__;
  }
  
  Future<String?> get_cityName() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_cityName", {'__this__': this});
    return __result__;
  }
  
  Future<int?> get_timeStamp() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_timeStamp", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_favId(String favId) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_favId', <String, dynamic>{'__this__': this, "favId": favId});
  
  
  }
  
  Future<void> set_poiName(String poiName) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_poiName', <String, dynamic>{'__this__': this, "poiName": poiName});
  
  
  }
  
  Future<void> set_poiUid(String poiUid) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_poiUid', <String, dynamic>{'__this__': this, "poiUid": poiUid});
  
  
  }
  
  Future<void> set_pt(CLLocationCoordinate2D pt) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_pt', <String, dynamic>{'__this__': this, "pt": pt});
  
  
  }
  
  Future<void> set_address(String address) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_address', <String, dynamic>{'__this__': this, "address": address});
  
  
  }
  
  Future<void> set_cityName(String cityName) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_cityName', <String, dynamic>{'__this__': this, "cityName": cityName});
  
  
  }
  
  Future<void> set_timeStamp(int timeStamp) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_timeStamp', <String, dynamic>{'__this__': this, "timeStamp": timeStamp});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'BMKFavPoiInfo{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension BMKFavPoiInfo_Batch on List<BMKFavPoiInfo> {
  String? get refId {
    if (isEmpty) return null;
    return first.refId;
  }

  //region getters
  Future<List<String?>> get_favId_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_favId_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<String?>> get_poiName_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_poiName_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<String?>> get_poiUid_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_poiUid_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<CLLocationCoordinate2D?>> get_pt_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_pt_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => BmapUtilsFluttifyIOSAs<CLLocationCoordinate2D>(__result__)).cast<CLLocationCoordinate2D?>().toList();
  }
  
  Future<List<String?>> get_address_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_address_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<String?>> get_cityName_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_cityName_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<int?>> get_timeStamp_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKFavPoiInfo::get_timeStamp_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<int?>().toList();
  }
  
  //endregion

  //region setters
  Future<void> set_favId_batch(List<String> favId) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_favId_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "favId": favId[__i__]}]);
  
  
  }
  
  Future<void> set_poiName_batch(List<String> poiName) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_poiName_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "poiName": poiName[__i__]}]);
  
  
  }
  
  Future<void> set_poiUid_batch(List<String> poiUid) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_poiUid_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "poiUid": poiUid[__i__]}]);
  
  
  }
  
  Future<void> set_pt_batch(List<CLLocationCoordinate2D> pt) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_pt_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "pt": pt[__i__]}]);
  
  
  }
  
  Future<void> set_address_batch(List<String> address) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_address_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "address": address[__i__]}]);
  
  
  }
  
  Future<void> set_cityName_batch(List<String> cityName) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_cityName_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "cityName": cityName[__i__]}]);
  
  
  }
  
  Future<void> set_timeStamp_batch(List<int> timeStamp) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKFavPoiInfo::set_timeStamp_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "timeStamp": timeStamp[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}