// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

extension BMKGeometryExtension on NSValue {
  //region constants
  static const String name__ = 'BMKGeometryExtension';

  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<BMKMapPoint?> BMKMapPointValue() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKGeometryExtension@$refId::BMKMapPointValue([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKGeometryExtension::BMKMapPointValue', {"__this__": this});
  
  
    // handle native call
  
  
    return BmapUtilsFluttifyIOSAs<BMKMapPoint>(__result__);
  }
  
  
  Future<BMKMapSize?> BMKMapSizeValue() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKGeometryExtension@$refId::BMKMapSizeValue([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKGeometryExtension::BMKMapSizeValue', {"__this__": this});
  
  
    // handle native call
  
  
    return BmapUtilsFluttifyIOSAs<BMKMapSize>(__result__);
  }
  
  
  Future<BMKMapRect?> BMKMapRectValue() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKGeometryExtension@$refId::BMKMapRectValue([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKGeometryExtension::BMKMapRectValue', {"__this__": this});
  
  
    // handle native call
  
  
    return BmapUtilsFluttifyIOSAs<BMKMapRect>(__result__);
  }
  
  
  Future<CLLocationCoordinate2D?> Coordinate2DValue() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKGeometryExtension@$refId::Coordinate2DValue([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKGeometryExtension::Coordinate2DValue', {"__this__": this});
  
  
    // handle native call
  
  
    return BmapUtilsFluttifyIOSAs<CLLocationCoordinate2D>(__result__);
  }
  
  //endregion
}