// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKLanguageType {
  BMKLanguageTypeChinese /* 0 */,
  BMKLanguageTypeEnglish /* 1 */
}

extension BMKLanguageTypeToX on BMKLanguageType {
  int toValue() {
    switch (this) {
      case BMKLanguageType.BMKLanguageTypeChinese: return 0;
      case BMKLanguageType.BMKLanguageTypeEnglish: return 1;
      default: return 0;
    }
  }
}

extension BMKLanguageTypeFromX on int {
  BMKLanguageType toBMKLanguageType() {
    switch (this) {
      case 0: return BMKLanguageType.BMKLanguageTypeChinese;
      case 1: return BMKLanguageType.BMKLanguageTypeEnglish;
      default: return BMKLanguageType.values[this + 0];
    }
  }
}