// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKMapRect extends NSObject  {
  //region constants
  static const String name__ = 'BMKMapRect';

  @override
  final String tag__ = 'bmap_utils_fluttify';

  
  //endregion

  //region creators
  static Future<BMKMapRect?> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod(
      'ObjectFactory::createBMKMapRect',
      {'init': init}
    );
    return BmapUtilsFluttifyIOSAs<BMKMapRect?>(__result__);
  }
  
  static Future<List<BMKMapRect>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kBmapUtilsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchBMKMapRect',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => BmapUtilsFluttifyIOSAs<BMKMapRect>(it))
        .where((element) => element !=null)
        .cast<BMKMapRect>()
        .toList() ?? <BMKMapRect>[];
  }
  
  //endregion

  //region getters
  Future<BMKMapPoint?> get_origin() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKMapRect::get_origin", {'__this__': this});
    return BmapUtilsFluttifyIOSAs<BMKMapPoint>(__result__);
  }
  
  Future<BMKMapSize?> get_size() async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod("BMKMapRect::get_size", {'__this__': this});
    return BmapUtilsFluttifyIOSAs<BMKMapSize>(__result__);
  }
  
  //endregion

  //region setters
  Future<void> set_origin(BMKMapPoint origin) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKMapRect::set_origin', <String, dynamic>{'__this__': this, "origin": origin});
  
  
  }
  
  Future<void> set_size(BMKMapSize size) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKMapRect::set_size', <String, dynamic>{'__this__': this, "size": size});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'BMKMapRect{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension BMKMapRect_Batch on List<BMKMapRect> {
  String? get refId {
    if (isEmpty) return null;
    return first.refId;
  }

  //region getters
  Future<List<BMKMapPoint?>> get_origin_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKMapRect::get_origin_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => BmapUtilsFluttifyIOSAs<BMKMapPoint>(__result__)).cast<BMKMapPoint?>().toList();
  }
  
  Future<List<BMKMapSize?>> get_size_batch() async {
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod("BMKMapRect::get_size_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => BmapUtilsFluttifyIOSAs<BMKMapSize>(__result__)).cast<BMKMapSize?>().toList();
  }
  
  //endregion

  //region setters
  Future<void> set_origin_batch(List<BMKMapPoint> origin) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKMapRect::set_origin_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "origin": origin[__i__]}]);
  
  
  }
  
  Future<void> set_size_batch(List<BMKMapSize> size) async {
    await kBmapUtilsFluttifyChannel.invokeMethod('BMKMapRect::set_size_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "size": size[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}