// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKMapModule {
  BMKMapModuleTile /* 0 */,
  BMKMapModuleBasic /* 1 */
}

extension BMKMapModuleToX on BMKMapModule {
  int toValue() {
    switch (this) {
      case BMKMapModule.BMKMapModuleTile: return 0;
      case BMKMapModule.BMKMapModuleBasic: return 1;
      default: return 0;
    }
  }
}

extension BMKMapModuleFromX on int {
  BMKMapModule toBMKMapModule() {
    switch (this) {
      case 0: return BMKMapModule.BMKMapModuleTile;
      case 1: return BMKMapModule.BMKMapModuleBasic;
      default: return BMKMapModule.values[this + 0];
    }
  }
}