// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_utils_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKNaviPara extends NSObject  {
  //region constants
  static const String name__ = 'BMKNaviPara';

  
  //endregion

  //region creators
  static Future<BMKNaviPara> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::createBMKNaviPara');
    final object = BMKNaviPara()..refId = refId..tag__ = 'bmap_utils_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKNaviPara>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::create_batchBMKNaviPara', {'length': length});
  
    final List<BMKNaviPara> typedResult = resultBatch.map((result) => BMKNaviPara()..refId = result..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<BMKPlanNode> get_startPoint() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_startPoint", {'refId': refId});
    kNativeObjectPool.add(BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify');
    return BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify';
  }
  
  Future<BMKPlanNode> get_endPoint() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_endPoint", {'refId': refId});
    kNativeObjectPool.add(BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify');
    return BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify';
  }
  
  Future<BMK_NAVI_TYPE> get_naviType() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_naviType", {'refId': refId});
  
    return BMK_NAVI_TYPE.values[__result__];
  }
  
  Future<String> get_appScheme() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_appScheme", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_appName() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_appName", {'refId': refId});
  
    return __result__;
  }
  
  Future<bool> get_isSupportWeb() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_isSupportWeb", {'refId': refId});
  
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_startPoint(BMKPlanNode startPoint) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_startPoint', {'refId': refId, "startPoint": startPoint.refId});
  
  
  }
  
  Future<void> set_endPoint(BMKPlanNode endPoint) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_endPoint', {'refId': refId, "endPoint": endPoint.refId});
  
  
  }
  
  Future<void> set_naviType(BMK_NAVI_TYPE naviType) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_naviType', {'refId': refId, "naviType": naviType.index});
  
  
  }
  
  Future<void> set_appScheme(String appScheme) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_appScheme', {'refId': refId, "appScheme": appScheme});
  
  
  }
  
  Future<void> set_appName(String appName) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_appName', {'refId': refId, "appName": appName});
  
  
  }
  
  Future<void> set_isSupportWeb(bool isSupportWeb) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_isSupportWeb', {'refId': refId, "isSupportWeb": isSupportWeb});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKNaviPara_Batch on List<BMKNaviPara> {
  //region getters
  Future<List<BMKPlanNode>> get_startPoint_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_startPoint_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<BMKPlanNode>> get_endPoint_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_endPoint_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => BMKPlanNode()..refId = __result__..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<BMK_NAVI_TYPE>> get_naviType_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_naviType_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => BMK_NAVI_TYPE.values[__result__]).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_appScheme_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_appScheme_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_appName_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_appName_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<bool>> get_isSupportWeb_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKNaviPara::get_isSupportWeb_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<bool>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_startPoint_batch(List<BMKPlanNode> startPoint) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_startPoint_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "startPoint": startPoint[__i__].refId}]);
  
  
  }
  
  Future<void> set_endPoint_batch(List<BMKPlanNode> endPoint) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_endPoint_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "endPoint": endPoint[__i__].refId}]);
  
  
  }
  
  Future<void> set_naviType_batch(List<BMK_NAVI_TYPE> naviType) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_naviType_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "naviType": naviType[__i__].index}]);
  
  
  }
  
  Future<void> set_appScheme_batch(List<String> appScheme) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_appScheme_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "appScheme": appScheme[__i__]}]);
  
  
  }
  
  Future<void> set_appName_batch(List<String> appName) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_appName_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "appName": appName[__i__]}]);
  
  
  }
  
  Future<void> set_isSupportWeb_batch(List<bool> isSupportWeb) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKNaviPara::set_isSupportWeb_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "isSupportWeb": isSupportWeb[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}