// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKOpenTransitPolicy {
  BMK_OPEN_TRANSIT_RECOMMAND,
  BMK_OPEN_TRANSIT_TRANSFER_FIRST,
  BMK_OPEN_TRANSIT_WALK_FIRST,
  BMK_OPEN_TRANSIT_NO_SUBWAY,
  BMK_OPEN_TRANSIT_TIME_FIRST
}