// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKOpenRoute extends NSObject  {
  //region constants
  static const String name__ = 'BMKOpenRoute';

  @override
  final String tag__ = 'bmap_utils_fluttify';

  
  //endregion

  //region creators
  static Future<BMKOpenRoute?> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod(
      'ObjectFactory::createBMKOpenRoute',
      {'init': init}
    );
    return BmapUtilsFluttifyIOSAs<BMKOpenRoute?>(__result__);
  }
  
  static Future<List<BMKOpenRoute>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kBmapUtilsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchBMKOpenRoute',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => BmapUtilsFluttifyIOSAs<BMKOpenRoute>(it))
        .where((element) => element !=null)
        .cast<BMKOpenRoute>()
        .toList() ?? <BMKOpenRoute>[];
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<BMKOpenErrorCode?> openBaiduMapWalkingRoute(BMKOpenWalkingRouteOption option) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKOpenRoute::openBaiduMapWalkingRoute([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapWalkingRoute', {"option": option});
  
  
    // handle native call
  
  
    return (__result__ as int).toBMKOpenErrorCode();
  }
  
  
  static Future<BMKOpenErrorCode?> openBaiduMapTransitRoute(BMKOpenTransitRouteOption option) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKOpenRoute::openBaiduMapTransitRoute([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapTransitRoute', {"option": option});
  
  
    // handle native call
  
  
    return (__result__ as int).toBMKOpenErrorCode();
  }
  
  
  static Future<BMKOpenErrorCode?> openBaiduMapDrivingRoute(BMKOpenDrivingRouteOption option) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: BMKOpenRoute::openBaiduMapDrivingRoute([])');
    }
  
    // invoke native method
    final __result__ = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapDrivingRoute', {"option": option});
  
  
    // handle native call
  
  
    return (__result__ as int).toBMKOpenErrorCode();
  }
  
  //endregion

  @override
  String toString() {
    return 'BMKOpenRoute{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension BMKOpenRoute_Batch on List<BMKOpenRoute> {
  String? get refId {
    if (isEmpty) return null;
    return first.refId;
  }

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<List<BMKOpenErrorCode?>> openBaiduMapWalkingRoute_batch(List<BMKOpenWalkingRouteOption> option) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapWalkingRoute_batch', [for (int __i__ = 0; __i__ < option.length; __i__++) {"option": option[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => (__result__ as int).toBMKOpenErrorCode()).cast<BMKOpenErrorCode?>().toList();
  }
  
  
  static Future<List<BMKOpenErrorCode?>> openBaiduMapTransitRoute_batch(List<BMKOpenTransitRouteOption> option) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapTransitRoute_batch', [for (int __i__ = 0; __i__ < option.length; __i__++) {"option": option[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => (__result__ as int).toBMKOpenErrorCode()).cast<BMKOpenErrorCode?>().toList();
  }
  
  
  static Future<List<BMKOpenErrorCode?>> openBaiduMapDrivingRoute_batch(List<BMKOpenDrivingRouteOption> option) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapUtilsFluttifyChannel.invokeMethod('BMKOpenRoute::openBaiduMapDrivingRoute_batch', [for (int __i__ = 0; __i__ < option.length; __i__++) {"option": option[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => (__result__ as int).toBMKOpenErrorCode()).cast<BMKOpenErrorCode?>().toList();
  }
  
  //endregion
}