// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKOpenTransitRouteOption extends BMKOpenRouteOption  {
  //region constants
  static const String name__ = 'BMKOpenTransitRouteOption';

  
  //endregion

  //region creators
  static Future<BMKOpenTransitRouteOption> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::createBMKOpenTransitRouteOption');
    final object = BMKOpenTransitRouteOption()..refId = refId..tag__ = 'bmap_utils_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKOpenTransitRouteOption>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::create_batchBMKOpenTransitRouteOption', {'length': length});
  
    final List<BMKOpenTransitRouteOption> typedResult = resultBatch.map((result) => BMKOpenTransitRouteOption()..refId = result..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<BMKOpenTransitPolicy> get_openTransitPolicy() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenTransitRouteOption::get_openTransitPolicy", {'refId': refId});
  
    return BMKOpenTransitPolicy.values[__result__];
  }
  
  //endregion

  //region setters
  Future<void> set_openTransitPolicy(BMKOpenTransitPolicy openTransitPolicy) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenTransitRouteOption::set_openTransitPolicy', {'refId': refId, "openTransitPolicy": openTransitPolicy.index});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKOpenTransitRouteOption_Batch on List<BMKOpenTransitRouteOption> {
  //region getters
  Future<List<BMKOpenTransitPolicy>> get_openTransitPolicy_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenTransitRouteOption::get_openTransitPolicy_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => BMKOpenTransitPolicy.values[__result__]).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_openTransitPolicy_batch(List<BMKOpenTransitPolicy> openTransitPolicy) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenTransitRouteOption::set_openTransitPolicy_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "openTransitPolicy": openTransitPolicy[__i__].index}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}