// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_utils_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKOpenPoiNearbyOption extends BMKOpenOption  {
  //region constants
  static const String name__ = 'BMKOpenPoiNearbyOption';

  
  //endregion

  //region creators
  static Future<BMKOpenPoiNearbyOption> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::createBMKOpenPoiNearbyOption');
    final object = BMKOpenPoiNearbyOption()..refId = refId..tag__ = 'bmap_utils_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKOpenPoiNearbyOption>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::create_batchBMKOpenPoiNearbyOption', {'length': length});
  
    final List<BMKOpenPoiNearbyOption> typedResult = resultBatch.map((result) => BMKOpenPoiNearbyOption()..refId = result..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<CLLocationCoordinate2D> get_location() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_location", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = __result__..tag__ = 'bmap_utils_fluttify');
    return CLLocationCoordinate2D()..refId = __result__..tag__ = 'bmap_utils_fluttify';
  }
  
  Future<int> get_radius() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_radius", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_keyword() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_keyword", {'refId': refId});
  
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_location(CLLocationCoordinate2D location) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_location', {'refId': refId, "location": location.refId});
  
  
  }
  
  Future<void> set_radius(int radius) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_radius', {'refId': refId, "radius": radius});
  
  
  }
  
  Future<void> set_keyword(String keyword) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_keyword', {'refId': refId, "keyword": keyword});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKOpenPoiNearbyOption_Batch on List<BMKOpenPoiNearbyOption> {
  //region getters
  Future<List<CLLocationCoordinate2D>> get_location_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_location_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => CLLocationCoordinate2D()..refId = __result__..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<int>> get_radius_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_radius_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_keyword_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPoiNearbyOption::get_keyword_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_location_batch(List<CLLocationCoordinate2D> location) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_location_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "location": location[__i__].refId}]);
  
  
  }
  
  Future<void> set_radius_batch(List<int> radius) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_radius_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "radius": radius[__i__]}]);
  
  
  }
  
  Future<void> set_keyword_batch(List<String> keyword) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPoiNearbyOption::set_keyword_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "keyword": keyword[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}