// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKOpenPanoramaOption extends BMKOpenOption  {
  //region constants
  static const String name__ = 'BMKOpenPanoramaOption';

  
  //endregion

  //region creators
  static Future<BMKOpenPanoramaOption> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::createBMKOpenPanoramaOption');
    final object = BMKOpenPanoramaOption()..refId = refId..tag__ = 'bmap_utils_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKOpenPanoramaOption>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('ObjectFactory::create_batchBMKOpenPanoramaOption', {'length': length});
  
    final List<BMKOpenPanoramaOption> typedResult = resultBatch.map((result) => BMKOpenPanoramaOption()..refId = result..tag__ = 'bmap_utils_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_poiUid() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPanoramaOption::get_poiUid", {'refId': refId});
  
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_poiUid(String poiUid) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPanoramaOption::set_poiUid', {'refId': refId, "poiUid": poiUid});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKOpenPanoramaOption_Batch on List<BMKOpenPanoramaOption> {
  //region getters
  Future<List<String>> get_poiUid_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod("BMKOpenPanoramaOption::get_poiUid_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_poiUid_batch(List<String> poiUid) async {
    await MethodChannel('com.fluttify/bmap_utils_fluttify').invokeMethod('BMKOpenPanoramaOption::set_poiUid_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "poiUid": poiUid[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}