// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKOpenTransitPolicy {
  BMK_OPEN_TRANSIT_RECOMMAND /* 3 */,
  BMK_OPEN_TRANSIT_TRANSFER_FIRST /* null */,
  BMK_OPEN_TRANSIT_WALK_FIRST /* null */,
  BMK_OPEN_TRANSIT_NO_SUBWAY /* null */,
  BMK_OPEN_TRANSIT_TIME_FIRST /* null */
}

extension BMKOpenTransitPolicyToX on BMKOpenTransitPolicy {
  int toValue() {
    switch (this) {
      case BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_RECOMMAND: return 3;
      case BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_TRANSFER_FIRST: return BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_TRANSFER_FIRST.index + 3;
      case BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_WALK_FIRST: return BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_WALK_FIRST.index + 3;
      case BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_NO_SUBWAY: return BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_NO_SUBWAY.index + 3;
      case BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_TIME_FIRST: return BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_TIME_FIRST.index + 3;
      default: return 0;
    }
  }
}

extension BMKOpenTransitPolicyFromX on int {
  BMKOpenTransitPolicy toBMKOpenTransitPolicy() {
    switch (this) {
      case 3: return BMKOpenTransitPolicy.BMK_OPEN_TRANSIT_RECOMMAND;
      default: return BMKOpenTransitPolicy.values[this + 3];
    }
  }
}