// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:bmap_utils_fluttify/src/ios/ios.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
extension TypeOpBmapUtilsFluttifyIOS on Object {
  // type check
  Future<bool> is__<T>() async {
    final typeName = T.toString();
    if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
      return this is T;
    }
    else if (T == BMKOpenRoute) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenRoute', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenPoi) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenPoi', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenPoiDetailOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenPoiDetailOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenPoiNearbyOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenPoiNearbyOption', {'__this__': this});
      return result;
    }
    else if (T == BMKFavPoiInfo) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKFavPoiInfo', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenRouteOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenRouteOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenWalkingRouteOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenWalkingRouteOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenDrivingRouteOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenDrivingRouteOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenTransitRouteOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenTransitRouteOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenPanoramaOption) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenPanoramaOption', {'__this__': this});
      return result;
    }
    else if (T == BMKOpenPanorama) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKOpenPanorama', {'__this__': this});
      return result;
    }
    else if (T == BMKFavPoiManager) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKFavPoiManager', {'__this__': this});
      return result;
    }
    else if (T == BMKNaviPara) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKNaviPara', {'__this__': this});
      return result;
    }
    else if (T == BMKNavigation) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfBMKNavigation', {'__this__': this});
      return result;
    }
    else if (T == CLLocation) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCLLocation', {'__this__': this});
      return result;
    }
    else if (T == CLHeading) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCLHeading', {'__this__': this});
      return result;
    }
    else if (T == CGRect) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCGRect', {'__this__': this});
      return result;
    }
    else if (T == CGPoint) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCGPoint', {'__this__': this});
      return result;
    }
    else if (T == CGSize) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCGSize', {'__this__': this});
      return result;
    }
    else if (T == UIEdgeInsets) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIEdgeInsets', {'__this__': this});
      return result;
    }
    else if (T == CLLocationCoordinate2D) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCLLocationCoordinate2D', {'__this__': this});
      return result;
    }
    else if (T == CLLocationManager) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfCLLocationManager', {'__this__': this});
      return result;
    }
    else if (T == NSError) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfNSError', {'__this__': this});
      return result;
    }
    else if (T == UIView) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIView', {'__this__': this});
      return result;
    }
    else if (T == UIViewController) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIViewController', {'__this__': this});
      return result;
    }
    else if (T == UIControl) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIControl', {'__this__': this});
      return result;
    }
    else if (T == UIImage) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIImage', {'__this__': this});
      return result;
    }
    else if (T == UIColor) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfUIColor', {'__this__': this});
      return result;
    }
    else if (T == NSData) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfNSData', {'__this__': this});
      return result;
    }
    else if (T == NSOperation) {
      final result = await MethodChannel('com.fluttify/bmap_utils_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('RefClass::isKindOfNSOperation', {'__this__': this});
      return result;
    }
  }

  // type cast
  T as__<T>() {
    final typeName = T.toString();
    // jsonable 直接造型 返回
    if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
      return this as T;
    }
    // 如果是Ref类的cast, 那么取其refId, 如果本身是refId, 那么直接使用(int)
    else if (T == BMKOpenRoute) {
      return (BMKOpenRoute()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenPoi) {
      return (BMKOpenPoi()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenPoiDetailOption) {
      return (BMKOpenPoiDetailOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenPoiNearbyOption) {
      return (BMKOpenPoiNearbyOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKFavPoiInfo) {
      return (BMKFavPoiInfo()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenRouteOption) {
      return (BMKOpenRouteOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenWalkingRouteOption) {
      return (BMKOpenWalkingRouteOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenDrivingRouteOption) {
      return (BMKOpenDrivingRouteOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenTransitRouteOption) {
      return (BMKOpenTransitRouteOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenOption) {
      return (BMKOpenOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenPanoramaOption) {
      return (BMKOpenPanoramaOption()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKOpenPanorama) {
      return (BMKOpenPanorama()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKFavPoiManager) {
      return (BMKFavPoiManager()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKNaviPara) {
      return (BMKNaviPara()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == BMKNavigation) {
      return (BMKNavigation()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CLLocation) {
      return (CLLocation()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CLHeading) {
      return (CLHeading()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CGRect) {
      return (CGRect()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CGPoint) {
      return (CGPoint()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CGSize) {
      return (CGSize()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIEdgeInsets) {
      return (UIEdgeInsets()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CLLocationCoordinate2D) {
      return (CLLocationCoordinate2D()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == CLLocationManager) {
      return (CLLocationManager()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == NSError) {
      return (NSError()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIView) {
      return (UIView()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIViewController) {
      return (UIViewController()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIControl) {
      return (UIControl()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIImage) {
      return (UIImage()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == UIColor) {
      return (UIColor()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == NSData) {
      return (NSData()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
    else if (T == NSOperation) {
      return (NSOperation()..refId = (this is Ref ? (this as Ref).refId : this as String)..tag__ = 'bmap_utils_fluttify') as T;
    }
  }
}